plugins:
  - serverless-dotenv-plugin
  - serverless-offline

service: scylla-webhook-whatsapp--server
provider:
  environment:
     GRAPH_API_TOKEN: ${.env:GRAPH_API_TOKEN}
     WEBHOOK_VERIFY_TOKEN: ${.env:WEBHOOK_VERIFY_TOKEN}
     DB_NAME: ${.env:DB_NAME}
     CONNECTION_STRING: ${.env:CONNECTION_STRING} 
     PASSPHRASE: ${.env:PASSPHRASE}
     BASE64_PRIVATE_KEY: ${.env:BASE64_PRIVATE_KEY}
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  memorySize: 128
functions:
  app:
    handler: server.handler
    events: 
       - http: ANY /
       - http: 'ANY {proxy+}'