plugins:
  - serverless-offline

service: scylla-whatsapp-webhook-server
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  memorySize: 128
functions:
  app:
    handler: server.handler
    events: 
       - http: ANY /
       - http: 'ANY {proxy+}'